// AUTO-GENERATED by scripts/sync-bookshelf-db.mjs on 2026-07-22
// Source: Goodreads user 38480050, shelf "read" + mybookshelf.dev spine DB.
// 4 real spines (self-hosted in /spines/), 8 faux.
// Re-run `npm run sync:books` to refresh. Drop your own scan at /spines/<slug>.png to override a book.

window.BOOKS = [
  {"title":"Demon Copperhead","author":"Barbara Kingsolver","spine":"/spines/DemonCopperhead-60194162-3kngUG4Q3m.jpeg","w":33,"spineColor":"#e6dfc8","coverColor":"#e6dfc8","tilt":-0.83},
  {"title":"Small Things Like These","author":"Claire Keegan","spine":"/spines/SmallThingsLikeThese-58639322-yKOqXRS6lU.jpeg","w":17,"spineColor":"#8e7f70","coverColor":"#8e7f70","tilt":1.17},
  {"title":"One Hundred Years of Solitude","author":"Gabriel García Márquez","spine":"/spines/OneHundredYearsofSolitude-320-OZY2WFx8V4.png","w":39,"spineColor":"#c7d193","coverColor":"#c7d193","tilt":1.06},
  {"title":"White Teeth","author":"Zadie Smith","spineColor":"hsl(99 67% 23%)","coverColor":"hsl(99 67% 23%)","text":"#ffffff","w":30,"cover":"/covers/auto/white-teeth.jpg","coverW":134,"tilt":1.19},
  {"title":"The Humans","author":"Matt Haig","spine":"/spines/the-humans.png","w":26,"tilt":1.06},
  {"title":"Just Mercy","author":"Bryan Stevenson","spineColor":"hsl(353 65% 38%)","coverColor":"hsl(353 65% 38%)","text":"#ffffff","w":29,"tilt":-0.93},
  {"title":"Player Piano","author":"Kurt Vonnegut Jr.","spineColor":"hsl(50 70% 43%)","coverColor":"hsl(50 70% 43%)","text":"#ffffff","w":30,"cover":"/covers/auto/player-piano.jpg","coverW":134,"tilt":0.7},
  {"title":"East of Eden","author":"John Steinbeck","spineColor":"hsl(269 77% 13%)","coverColor":"hsl(269 77% 13%)","text":"#ffffff","w":30,"cover":"/covers/auto/east-of-eden.jpg","coverW":137,"tilt":0.89},
  {"title":"Mother Night","author":"Kurt Vonnegut Jr.","spineColor":"hsl(209 71% 15%)","coverColor":"hsl(209 71% 15%)","text":"#ffffff","w":30,"cover":"/covers/auto/mother-night.jpg","coverW":139,"tilt":0.69},
  {"title":"Cat’s Cradle","author":"Kurt Vonnegut Jr.","spineColor":"hsl(49 75% 21%)","coverColor":"hsl(49 75% 21%)","text":"#ffffff","w":30,"tilt":0.69},
  {"title":"2666","author":"Roberto Bolaño","spineColor":"hsl(311 73% 48%)","coverColor":"hsl(311 73% 48%)","text":"#ffffff","w":25,"cover":"/covers/auto/2666.jpg","coverW":133,"tilt":-1.31},
  {"title":"The Unbearable Lightness of Being","author":"Milan Kundera","spineColor":"hsl(86 52% 25%)","coverColor":"hsl(86 52% 25%)","text":"#ffffff","w":44,"cover":"/covers/auto/the-unbearable-lightness-of-being.jpg","coverW":134,"tilt":1.06},
]
